process PREPROCESS_FASTQ {
    container "ghcr.io/ch99l/bambu-pipe-preprocess:latest"
    label "medium_cpu"
    label "medium_mem"
    label "long"

    publishDir params.output_dir,
        mode: 'symlink',
        enabled: params.save_intermediates
    
    input:
    tuple val(sample), path(fastq), val(meta), path(whitelist)
    path(flank_seq_config)
    path(adapter_seq_config)

    output:
    tuple val(sample), path("${sample}_preprocessed_reads.fastq.gz"), val(meta), emit: fastq
    path("*_intermediate_*"), optional: true

    script:
    """
    #=======================================================================================================
    # Helper functions (All functions read from stdin and write to stdout)
    #=======================================================================================================
    # Decompress input FASTQ using parallel gzip (pigz) for faster processing
    decompress() {
        if [[ $fastq == *.gz ]]; then
            pigz -p $task.cpus -d -c $fastq
        else
            cat $fastq
        fi  
    } 

    # Saves intermediate files, otherwise passes data through without saving to disk (for development and testing purposes)
    # Arguments: 1=output file name for intermediate file
    save_intermediate() {
        local out_file=\$1
        if [[ $params.save_intermediates == "true" ]]; then
            tee >(pigz -p $task.cpus -c > \$out_file)
        else
            cat
        fi
    }
        
    # FASTQ quality score filtering with chopper (Optional)
    chopper_cmd() {
        if [[ $params.qscore_filtering == "true" ]]; then
            chopper -q $params.qfilter_threshold -t $task.cpus
        else
            cat
        fi
    }

    # Demultiplexing with flexiplex
    # Arguments: 1=barcode list file generated by flexiplex-filter
    flexiplex_demux() {
        local barcode_list=\$1
        if [[ $meta.chemistry == 10x5* ]]; then
            flexiplex_f=$params.flexiplex_f_5prime
        else
            flexiplex_f=$params.flexiplex_f_3prime
        fi

        flexiplex -p $task.cpus -k \$barcode_list \$flank_seq -f \$flexiplex_f -e $params.flexiplex_e -
    }

    # Trims reverse primer with cutadapt
    cutadapt_trim() {
        cutadapt -a \$rev_primer_f --cores $task.cpus -
    }

    # Re-searches all primer and TSO sequences to remove non-standard reads 
    cutadapt_re_search() {
        if [[ $meta.chemistry == 10x5* ]]; then
            args="-b \$fwd_primer_f -b \$fwd_primer_r -b \$TSO_f -b \$TSO_r -b \$rev_primer_f -b \$rev_primer_r"
        else
            args="-b \$fwd_primer_f -b \$fwd_primer_r -b \$rev_primer_f -b \$rev_primer_r"
        fi
        
        cutadapt \$args --action none --discard --cores $task.cpus -
    }

    # Reverse complements FASTQ reads to orient them in the transcript direction (for 3' and visium chemistries only)
    reverse_complement() {
        if [[ $meta.chemistry == 10x5* ]]; then
            cat # For 5' kits, reads are already in the transcript direction
        else
            reverse_complement_fastq.py # For 3' kits, orient reads in transcript direction to improve minimap alignment
        fi
        
    }

    #=======================================================================================================
    # Executing preprocessing steps (Pipe stdin/stdout to avoid writing large intermediate files to disk)
    #=======================================================================================================
    # Chain commands: Decompression -> (Optional) Quality score filtering with chopper -> (Optional) Save intermediate file after quality filtering
    decompress | chopper_cmd | save_intermediate "${sample}_intermediate_qfilter.fastq.gz" > ${sample}_chopper_out.fastq

    # Extract chemistry specfic parameters from config files
    IFS=',' read -r _ left_flank barcode umi right_flank < <(awk -F',' -v chem=$meta.chemistry '\$1 == chem' $flank_seq_config)
    IFS=',' read -r _ fwd_primer_f fwd_primer_r rev_primer_f rev_primer_r TSO_f TSO_r < <(awk -F',' -v chem=$meta.chemistry '\$1 == chem' $adapter_seq_config)
    flank_seq="-x \$left_flank -b \$barcode -u \$umi -x \$right_flank"

    # Flexiplex filter (barcode filtering)
	flexiplex -p $task.cpus \$flank_seq -f 0 ${sample}_chopper_out.fastq
	flexiplex-filter -w $whitelist --outfile my_filtered_barcode_list.txt flexiplex_barcodes_counts.txt

    # Chain commands: Flexiplex demultiplexing -> (Optional) Save intermediate file after flexiplex -> Cutadapt trimming of reverse primer -> \
    # Cutadapt re-search for all primer and TSO sequences to remove non-standard reads -> Reverse complementation of reads for 3' and visium chemistry -> Compression with pigz
    cat ${sample}_chopper_out.fastq | 
    flexiplex_demux my_filtered_barcode_list.txt | 
    save_intermediate "${sample}_intermediate_flexiplex.fastq.gz" | 
    cutadapt_trim | 
    cutadapt_re_search | 
    reverse_complement | 
    pigz -p $task.cpus -c > ${sample}_preprocessed_reads.fastq.gz

    rm ${sample}_chopper_out.fastq
    """
}